from enum import StrEnum


class AuditAction(StrEnum):
    """
    Ações auditáveis.

    O valor é gravado como texto (sem `choices` no model) para que novas ações
    não exijam migrations.
    """

    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGOUT = "LOGOUT"
    ACCESS_DENIED = "ACCESS_DENIED"

    WORK_SESSION_STARTED = "WORK_SESSION_STARTED"
    WORK_SESSION_ENDED = "WORK_SESSION_ENDED"

    PATIENT_CREATED = "PATIENT_CREATED"
    PATIENT_UPDATED = "PATIENT_UPDATED"

    APPOINTMENT_CREATED = "APPOINTMENT_CREATED"
    APPOINTMENT_UPDATED = "APPOINTMENT_UPDATED"

    CHECK_IN_CREATED = "CHECK_IN_CREATED"
    ENCOUNTER_STATUS_CHANGED = "ENCOUNTER_STATUS_CHANGED"
    ENCOUNTER_STARTED = "ENCOUNTER_STARTED"
    ENCOUNTER_COMPLETED = "ENCOUNTER_COMPLETED"

    QUEUE_TICKET_CALLED = "QUEUE_TICKET_CALLED"
    QUEUE_ENTRY_FORWARDED = "QUEUE_ENTRY_FORWARDED"
    QUEUE_ENTRY_NO_SHOW = "QUEUE_ENTRY_NO_SHOW"

    MEDICAL_RECORD_VIEW_GRANTED = "MEDICAL_RECORD_VIEW_GRANTED"
    MEDICAL_RECORD_VIEW_DENIED = "MEDICAL_RECORD_VIEW_DENIED"
    CLINICAL_NOTE_CREATED = "CLINICAL_NOTE_CREATED"

    PROCEDURE_RECORD_VIEW_GRANTED = "PROCEDURE_RECORD_VIEW_GRANTED"
    PROCEDURE_RECORD_VIEW_DENIED = "PROCEDURE_RECORD_VIEW_DENIED"
    PROCEDURE_RECORD_SAVED = "PROCEDURE_RECORD_SAVED"
