# Generated by Django 6.1.1 on 2026-09-28 18:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_code', models.CharField(max_length=12, verbose_name='senha')),
                ('service_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='data do atendimento')),
                ('status', models.CharField(choices=[('CHECK_IN_REALIZADO', 'Check-in realizado'), ('AGUARDANDO_PROFISSIONAL', 'Aguardando profissional'), ('CHAMADO', 'Chamado'), ('EM_ATENDIMENTO', 'Em atendimento'), ('ATENDIDO', 'Atendido'), ('NAO_COMPARECEU', 'Não compareceu'), ('CANCELADO', 'Cancelado')], default='CHECK_IN_REALIZADO', max_length=32)),
                ('checked_in_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='chegada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='finalização')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounter', to='scheduling.appointment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='patients.patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='professionals.professional')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='professionals.specialty')),
            ],
            options={
                'verbose_name': 'atendimento',
                'verbose_name_plural': 'atendimentos',
                'ordering': ('checked_in_at',),
            },
        ),
        migrations.CreateModel(
            name='EncounterStatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, default='', max_length=32)),
                ('new_status', models.CharField(choices=[('CHECK_IN_REALIZADO', 'Check-in realizado'), ('AGUARDANDO_PROFISSIONAL', 'Aguardando profissional'), ('CHAMADO', 'Chamado'), ('EM_ATENDIMENTO', 'Em atendimento'), ('ATENDIDO', 'Atendido'), ('NAO_COMPARECEU', 'Não compareceu'), ('CANCELADO', 'Cancelado')], max_length=32)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to='encounters.encounter')),
            ],
            options={
                'verbose_name': 'mudança de status do atendimento',
                'verbose_name_plural': 'mudanças de status do atendimento',
                'ordering': ('changed_at',),
            },
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['professional', 'status'], name='encounter_professional_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['service_date', 'status'], name='encounter_service_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.UniqueConstraint(fields=('service_date', 'ticket_code'), name='encounter_unique_daily_ticket'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['CHECK_IN_REALIZADO', 'AGUARDANDO_PROFISSIONAL', 'CHAMADO', 'EM_ATENDIMENTO', 'ATENDIDO', 'NAO_COMPARECEU', 'CANCELADO'])), name='encounter_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ATENDIDO'), _negated=True), ('completed_at__isnull', False), _connector='OR'), name='encounter_completed_has_timestamp'),
        ),
    ]
