# Generated by Django 6.1.1 on 2026-09-29 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='laterality',
            field=models.CharField(blank=True, choices=[('DIREITA', 'Direita'), ('ESQUERDA', 'Esquerda'), ('BILATERAL', 'Bilateral')], default='', max_length=16, verbose_name='lateralidade'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='with_sedation',
            field=models.BooleanField(default=False, verbose_name='com sedação'),
        ),
    ]
