# Generated by Django 6.1.1 on 2026-09-29 16:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('encounters', '0002_add_catalog_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('values', models.JSONField(default=dict, verbose_name='valores')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedure_records', to='encounters.encounter')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.executionformtemplate')),
            ],
            options={
                'verbose_name': 'registro de procedimento',
                'verbose_name_plural': 'registros de procedimento',
                'ordering': ('-recorded_at',),
                'indexes': [models.Index(fields=['encounter', '-recorded_at'], name='procedure_record_latest_idx')],
            },
        ),
    ]
