# Generated by Django 6.1.1 on 2026-09-28 18:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('professionals', '0001_initial'),
        ('workstations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue_type', models.CharField(choices=[('RECEPTION', 'Recepção'), ('CLINICAL', 'Clínica')], max_length=16)),
                ('status', models.CharField(choices=[('WAITING', 'Aguardando'), ('CALLED', 'Chamado'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='WAITING', max_length=16)),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='encounters.encounter')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='professionals.professional')),
            ],
            options={
                'verbose_name': 'entrada na fila',
                'verbose_name_plural': 'entradas na fila',
                'ordering': ('entered_at',),
            },
        ),
        migrations.CreateModel(
            name='QueueCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_type', models.CharField(choices=[('RECEPTION_DESK', 'Guichê de recepção'), ('CONSULTATION_ROOM', 'Consultório')], max_length=32)),
                ('destination_id', models.UUIDField()),
                ('destination_label', models.CharField(max_length=64)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('called_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('called_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_calls', to='workstations.worksession')),
                ('queue_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='queues.queueentry')),
            ],
            options={
                'verbose_name': 'chamada',
                'verbose_name_plural': 'chamadas',
                'ordering': ('-called_at',),
            },
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['queue_type', 'status', 'entered_at'], name='queue_entry_list_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['professional', 'status'], name='queue_entry_professional_idx'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('WAITING', 'CALLED'))), fields=('encounter', 'queue_type'), name='queue_entry_one_active_per_queue'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('queue_type', 'CLINICAL'), _negated=True), ('professional__isnull', False), _connector='OR'), name='queue_entry_clinical_has_professional'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['WAITING', 'CALLED', 'FINISHED', 'CANCELLED'])), name='queue_entry_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.CheckConstraint(condition=models.Q(('queue_type__in', ['RECEPTION', 'CLINICAL'])), name='queue_entry_type_valid'),
        ),
        migrations.AddIndex(
            model_name='queuecall',
            index=models.Index(fields=['-called_at'], name='queue_call_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='queuecall',
            constraint=models.UniqueConstraint(fields=('queue_entry', 'attempt_number'), name='queue_call_unique_attempt'),
        ),
    ]
