# Generated by Django 6.1.1 on 2026-09-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
        ('professionals', '0001_initial'),
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='queueentry',
            name='queue_entry_status_valid',
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Aguardando'), ('CALLED', 'Chamado'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado'), ('NO_SHOW', 'Não compareceu')], default='WAITING', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['WAITING', 'CALLED', 'FINISHED', 'CANCELLED', 'NO_SHOW'])), name='queue_entry_status_valid'),
        ),
    ]
