# Generated by Django 6.1.1 on 2026-09-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_add_no_show_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuecall',
            name='destination_type',
            field=models.CharField(choices=[('RECEPTION_DESK', 'Guichê de recepção'), ('CONSULTATION_ROOM', 'Consultório'), ('EXAM_ROOM', 'Sala de exames')], max_length=32),
        ),
    ]
