# Generated by Django 6.1.1 on 2026-09-28 18:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de auditoria',
                'verbose_name_plural': 'eventos de auditoria',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['-timestamp'], name='audit_event_timestamp_idx'), models.Index(fields=['action', '-timestamp'], name='audit_event_action_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_event_entity_idx'), models.Index(fields=['user', '-timestamp'], name='audit_event_user_idx')],
            },
        ),
    ]
