# Generated by Django 6.1.1 on 2026-09-30 01:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0002_add_catalog_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsurer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'convênio',
                'verbose_name_plural': 'convênios',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EncounterBilling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payer_type', models.CharField(choices=[('PARTICULAR', 'Particular'), ('CONVENIO', 'Convênio')], max_length=16, verbose_name='pagador')),
                ('guide_number', models.CharField(blank=True, default='', max_length=40, verbose_name='número da guia')),
                ('payment_method', models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('CARTAO_DEBITO', 'Cartão de débito'), ('CARTAO_CREDITO', 'Cartão de crédito')], default='', max_length=16, verbose_name='forma de pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('LIBERADO', 'Liberado')], default='PENDENTE', max_length=16)),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='pago/liberado em')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing', to='encounters.encounter')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('insurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.healthinsurer')),
            ],
            options={
                'verbose_name': 'financeiro do atendimento',
                'verbose_name_plural': 'financeiro dos atendimentos',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='billing_amount_not_negative'), models.CheckConstraint(condition=models.Q(models.Q(('insurer__isnull', True), ('payer_type', 'PARTICULAR')), models.Q(('insurer__isnull', False), ('payer_type', 'CONVENIO')), _connector='OR'), name='billing_insurer_matches_payer'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'PAGO'), _negated=True), models.Q(('payment_method', ''), _negated=True), _connector='OR'), name='billing_paid_has_method'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'LIBERADO'), _negated=True), models.Q(('payer_type', 'CONVENIO'), models.Q(('guide_number', ''), _negated=True)), _connector='OR'), name='billing_released_has_guide'), models.CheckConstraint(condition=models.Q(('status__in', ['PENDENTE', 'PAGO', 'LIBERADO'])), name='billing_status_valid')],
            },
        ),
    ]
