# Generated by Django 6.1.1 on 2026-09-29 15:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionFormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'formulário de execução',
                'verbose_name_plural': 'formulários de execução',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'área do catálogo',
                'verbose_name_plural': 'áreas do catálogo',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nome')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'pacote',
                'verbose_name_plural': 'pacotes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LaboratoryExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nome')),
                ('group', models.CharField(max_length=100, verbose_name='grupo')),
                ('sample_type', models.CharField(choices=[('SANGUE', 'Sangue'), ('URINA', 'Urina'), ('FEZES', 'Fezes'), ('OUTRO', 'Outro')], max_length=16, verbose_name='amostra')),
                ('preparation', models.TextField(blank=True, default='', verbose_name='preparo')),
                ('fasting_hours', models.PositiveSmallIntegerField(default=0, verbose_name='jejum (horas)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'exame laboratorial',
                'verbose_name_plural': 'exames laboratoriais',
                'ordering': ('group', 'name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('sample_type__in', ['SANGUE', 'URINA', 'FEZES', 'OUTRO'])), name='laboratory_exam_sample_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='catalog.servicecategory')),
            ],
            options={
                'verbose_name': 'grupo de serviços',
                'verbose_name_plural': 'grupos de serviços',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('service_type', models.CharField(choices=[('CONSULTA', 'Consulta'), ('SESSAO', 'Sessão'), ('PROCEDIMENTO', 'Procedimento'), ('EXAME', 'Exame')], max_length=16, verbose_name='tipo')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30, verbose_name='duração (min)')),
                ('reference_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preço de referência')),
                ('requires_laterality', models.BooleanField(default=False, verbose_name='exige lateralidade')),
                ('allows_sedation', models.BooleanField(default=False, verbose_name='permite sedação')),
                ('is_laboratory_collection', models.BooleanField(default=False, verbose_name='coleta laboratorial')),
                ('preparation_instructions', models.TextField(blank=True, default='', verbose_name='preparo')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('form_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.executionformtemplate', verbose_name='formulário de execução')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='professionals.specialty')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.servicegroup')),
            ],
            options={
                'verbose_name': 'serviço',
                'verbose_name_plural': 'serviços',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ServicePackageItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('laboratory_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.laboratoryexam')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.servicepackage')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.service')),
            ],
            options={
                'verbose_name': 'item do pacote',
                'verbose_name_plural': 'itens do pacote',
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='ExecutionFormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(verbose_name='chave')),
                ('label', models.CharField(max_length=100, verbose_name='rótulo')),
                ('field_type', models.CharField(choices=[('TEXT', 'Texto curto'), ('TEXTAREA', 'Texto longo'), ('NUMBER', 'Número'), ('BOOLEAN', 'Sim/Não'), ('SELECT', 'Lista de opções'), ('TIME', 'Horário')], max_length=16, verbose_name='tipo')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='unidade')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='opções')),
                ('is_required', models.BooleanField(default=False, verbose_name='obrigatório')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='catalog.executionformtemplate')),
            ],
            options={
                'verbose_name': 'campo do formulário',
                'verbose_name_plural': 'campos do formulário',
                'ordering': ('display_order', 'label'),
                'constraints': [models.UniqueConstraint(fields=('template', 'key'), name='form_field_unique_key'), models.CheckConstraint(condition=models.Q(('field_type__in', ['TEXT', 'TEXTAREA', 'NUMBER', 'BOOLEAN', 'SELECT', 'TIME'])), name='form_field_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='ServiceAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='sinônimo')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.service')),
            ],
            options={
                'verbose_name': 'sinônimo',
                'verbose_name_plural': 'sinônimos',
                'constraints': [models.UniqueConstraint(fields=('service', 'name'), name='service_alias_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='servicegroup',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='service_group_unique_name'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='service_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='service_unique_name_in_group'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('service_type__in', ['CONSULTA', 'SESSAO', 'PROCEDIMENTO', 'EXAME'])), name='service_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='service_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('reference_price__isnull', True), ('reference_price__gte', 0), _connector='OR'), name='service_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='servicepackageitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('laboratory_exam__isnull', True), ('service__isnull', False)), models.Q(('laboratory_exam__isnull', False), ('service__isnull', True)), _connector='OR'), name='package_item_service_xor_exam'),
        ),
    ]
