# Generated by Django 6.1.1 on 2026-09-28 18:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='nome completo')),
                ('social_name', models.CharField(blank=True, default='', max_length=200, verbose_name='nome social')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='data de nascimento')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='telefone')),
                ('mother_name', models.CharField(blank=True, default='', max_length=200, verbose_name='nome da mãe')),
                ('administrative_notes', models.TextField(blank=True, default='', verbose_name='observações administrativas')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ('full_name',),
                'indexes': [models.Index(fields=['full_name'], name='patient_full_name_idx'), models.Index(fields=['birth_date'], name='patient_birth_date_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cpf__isnull', False)), fields=('cpf',), name='patient_unique_cpf'), models.CheckConstraint(condition=models.Q(('cpf__isnull', True), ('cpf__regex', '^\\d{11}$'), _connector='OR'), name='patient_cpf_digits_only')],
            },
        ),
    ]
