# Generated by Django 6.1.1 on 2026-09-28 18:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('station_type', models.CharField(choices=[('RECEPTION_DESK', 'Guichê de recepção'), ('CONSULTATION_ROOM', 'Consultório')], max_length=32, verbose_name='tipo')),
                ('name', models.CharField(max_length=64, verbose_name='nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'posto de trabalho',
                'verbose_name_plural': 'postos de trabalho',
                'ordering': ('station_type', 'name'),
                'constraints': [models.UniqueConstraint(fields=('station_type', 'name'), name='station_unique_name'), models.CheckConstraint(condition=models.Q(('station_type__in', ['RECEPTION_DESK', 'CONSULTATION_ROOM'])), name='station_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('station_type', models.CharField(choices=[('RECEPTION_DESK', 'Guichê de recepção'), ('CONSULTATION_ROOM', 'Consultório')], max_length=32)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions', to='workstations.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sessão de trabalho',
                'verbose_name_plural': 'sessões de trabalho',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['station', '-started_at'], name='work_session_station_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user',), name='work_session_one_open_per_user'), models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='work_session_ends_after_start')],
            },
        ),
    ]
