# Generated by Django 6.1.1 on 2026-09-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='station',
            name='station_type_valid',
        ),
        migrations.AlterField(
            model_name='station',
            name='station_type',
            field=models.CharField(choices=[('RECEPTION_DESK', 'Guichê de recepção'), ('CONSULTATION_ROOM', 'Consultório'), ('EXAM_ROOM', 'Sala de exames')], max_length=32, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='station_type',
            field=models.CharField(choices=[('RECEPTION_DESK', 'Guichê de recepção'), ('CONSULTATION_ROOM', 'Consultório'), ('EXAM_ROOM', 'Sala de exames')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.CheckConstraint(condition=models.Q(('station_type__in', ['RECEPTION_DESK', 'CONSULTATION_ROOM', 'EXAM_ROOM'])), name='station_type_valid'),
        ),
    ]
