# Generated by Django 6.1.1 on 2026-09-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='accounts_user_role_valid',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ATENDENTE', 'Atendente'), ('MEDICO', 'Médico'), ('PROFISSIONAL_SAUDE', 'Profissional de saúde'), ('TECNICO', 'Técnico de exames'), ('GESTOR', 'Gestor')], max_length=32, verbose_name='perfil'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['ATENDENTE', 'MEDICO', 'PROFISSIONAL_SAUDE', 'TECNICO', 'GESTOR'])), name='accounts_user_role_valid'),
        ),
    ]
