# Generated by Django 6.1.1 on 2026-09-28 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_for', models.DateTimeField(verbose_name='data e horário')),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONFIRMADO', 'Confirmado'), ('CHECK_IN_REALIZADO', 'Check-in realizado'), ('CANCELADO', 'Cancelado'), ('NAO_COMPARECEU', 'Não compareceu')], default='AGENDADO', max_length=32)),
                ('notes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='professionals.professional')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='professionals.specialty')),
            ],
            options={
                'verbose_name': 'agendamento',
                'verbose_name_plural': 'agendamentos',
                'ordering': ('scheduled_for',),
                'indexes': [models.Index(fields=['scheduled_for'], name='appointment_scheduled_idx'), models.Index(fields=['professional', 'scheduled_for'], name='appointment_professional_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['AGENDADO', 'CONFIRMADO', 'CHECK_IN_REALIZADO', 'CANCELADO', 'NAO_COMPARECEU'])), name='appointment_status_valid')],
            },
        ),
    ]
