# Generated by Django 6.1.1 on 2026-09-29 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='laboratory_exams',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='catalog.laboratoryexam', verbose_name='exames laboratoriais'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='laterality',
            field=models.CharField(blank=True, choices=[('DIREITA', 'Direita'), ('ESQUERDA', 'Esquerda'), ('BILATERAL', 'Bilateral')], default='', max_length=16, verbose_name='lateralidade'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='with_sedation',
            field=models.BooleanField(default=False, verbose_name='com sedação'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('laterality', ''), ('laterality__in', ['DIREITA', 'ESQUERDA', 'BILATERAL']), _connector='OR'), name='appointment_laterality_valid'),
        ),
    ]
