# Generated by Django 6.1.1 on 2026-09-28 18:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('ticket_prefix', models.CharField(max_length=6, unique=True, verbose_name='prefixo da senha')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'especialidade',
                'verbose_name_plural': 'especialidades',
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('ticket_prefix__regex', '^[A-Z]{2,6}$')), name='specialty_ticket_prefix_format')],
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('council_registration', models.CharField(blank=True, default='', max_length=32, verbose_name='registro no conselho')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
                ('specialties', models.ManyToManyField(related_name='professionals', to='professionals.specialty')),
            ],
            options={
                'verbose_name': 'profissional',
                'verbose_name_plural': 'profissionais',
            },
        ),
    ]
